[package]
name = "convergence-poc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
convergence = "0.9.1"
async-trait = "0.1.60"
sqlparser = "0.29"

